# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'quupe' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quupe
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Batch', '~> 1.5.4'
  pod 'JSQMessagesViewController'
  pod 'Stripe'

  target 'quupeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'quupeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
